# Generated by Django 5.2.7 on 2025-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
